-- Generated by Oracle SQL Developer Data Modeler 19.4.0.350.1424
--   at:        2020-05-24 22:58:57 EEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE artist (
    artist_id    INTEGER NOT NULL,
    artist_name  VARCHAR2(400)
)
LOGGING;

ALTER TABLE artist ADD CONSTRAINT artist_pk PRIMARY KEY ( artist_id );

CREATE TABLE artwork (
    artwork_id             INTEGER NOT NULL,
    artwork_title          VARCHAR2(700) NOT NULL,
    artwork_creation_year  INTEGER,
    acqusition_date        DATE,
    proc_officer_name      VARCHAR2(400) NOT NULL
)
LOGGING;

ALTER TABLE artwork ADD CONSTRAINT artwork_pk PRIMARY KEY ( artwork_id );

CREATE TABLE proc_officer (
    proc_officer_name VARCHAR2(700) NOT NULL
)
LOGGING;

ALTER TABLE proc_officer ADD CONSTRAINT proc_officer_pk PRIMARY KEY ( proc_officer_name );

CREATE TABLE relation_ao (
    proc_officer_name   VARCHAR2(700) NOT NULL,
    artwork_artwork_id  INTEGER NOT NULL
)
LOGGING;

ALTER TABLE relation_ao ADD CONSTRAINT relation_artwork_officer_pk PRIMARY KEY ( proc_officer_name,
                                                                                 artwork_artwork_id );

CREATE TABLE relation_artwork_artist (
    artwork_artwork_id  INTEGER NOT NULL,
    artist_artist_id    INTEGER NOT NULL
)
LOGGING;

ALTER TABLE relation_artwork_artist ADD CONSTRAINT relation_1_pk PRIMARY KEY ( artwork_artwork_id,
                                                                               artist_artist_id );

ALTER TABLE relation_artwork_artist
    ADD CONSTRAINT relation_1_artist_fk FOREIGN KEY ( artist_artist_id )
        REFERENCES artist ( artist_id )
    NOT DEFERRABLE;

ALTER TABLE relation_artwork_artist
    ADD CONSTRAINT relation_1_artwork_fk FOREIGN KEY ( artwork_artwork_id )
        REFERENCES artwork ( artwork_id )
    NOT DEFERRABLE;

ALTER TABLE relation_ao
    ADD CONSTRAINT relation_ao_fk FOREIGN KEY ( artwork_artwork_id )
        REFERENCES artwork ( artwork_id )
    NOT DEFERRABLE;

ALTER TABLE relation_ao
    ADD CONSTRAINT relation_po_fk FOREIGN KEY ( proc_officer_name )
        REFERENCES proc_officer ( proc_officer_name )
    NOT DEFERRABLE;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             5
-- CREATE INDEX                             0
-- ALTER TABLE                              9
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0

commit;