CREATE OR REPLACE VIEW ARTIST_ARTWORK AS
SELECT ARTIST_ID, ARTIST_NAME, ARTWORK_ID, ARTWORK_TITLE, ARTWORK_CREATION_YEAR, ACQUSITION_DATE, PROC_OFFICER_NAME
FROM ARTIST
         LEFT JOIN RELATION_ARTWORK_ARTIST RAA on ARTIST.ARTIST_ID = RAA.ARTIST_ARTIST_ID
         RIGHT JOIN ARTWORK ON RAA.ARTWORK_ARTWORK_ID = ARTWORK.ARTWORK_ID;

CREATE OR REPLACE VIEW PROC_OFFICER_ARTWORK AS
SELECT PROC_OFFICER.PROC_OFFICER_NAME,
       ARTWORK.ARTWORK_ID,
       ARTWORK.ARTWORK_TITLE,
       ARTWORK.ARTWORK_CREATION_YEAR,
       ARTWORK.ACQUSITION_DATE,
       all_count
FROM PROC_OFFICER
         JOIN RELATION_AO ON PROC_OFFICER.PROC_OFFICER_NAME = RELATION_AO.PROC_OFFICER_NAME
         JOIN ARTWORK ON RELATION_AO.ARTWORK_ARTWORK_ID = ARTWORK.ARTWORK_ID
   , (select count(ARTWORK_ID) all_count from ARTWORK); 
commit;
/
